version: '3'

services:
  api-gateway:
    # container_name: api-gateway
    # build: ./api-gateway
    # image: mazinoukah/scratch_pay_apigateway:v1.0
    image: mazinoukah/scratch_pay_apigateway:v2.0
    volumes:
      - ../api-gateway:/var/www/api-gateway
    ports:
      - "4500:80"
    networks:
      - webgateway

  logger-interface:
    # container_name: logger-interface
    # build: ./logger-interface
    # image: mazinoukah/scratch_pay_logger_interface:v1.0
    image: mazinoukah/scratch_pay_logger_interface:v2.0
    volumes:
      - ../logger-interface:/var/www/logger-interface
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - webgateway

  pubsub-interface:
    # build: ./pubsub-interface
    image: mazinoukah/scratch_pay_pubsub_interface:v1.0
    volumes:
      - ../pubsub-interface:/var/www/pubsub-interface
    networks:
      - webgateway
    depends_on:
      - redis
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    # environment:
    #   - REDIS_HOST=redis

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
    # container_name: cache
    ports:
      - "6379:6379"


volumes:
  redis_data:

networks:
  webgateway:
    external: true